spring:
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    host: rabbitmq
    port: 5672
    addresses: ${RMQ_ADDRESS}

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
  config:
    activate:
      on-profile: prod